name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.1'

    - name: Install Dependencies
      run: npm install
      working-directory: ./express-authentication

    - name: Run Tests
      run: npm test
      working-directory: ./express-authentication

    - name: Start Application
      run: npm start
      working-directory: ./express-authentication

